CMake Error at /home/thanhvo/esp/esp-idf/tools/cmake/build.cmake:610 (message):
  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/__main__.py", line 6, in <module>
      main()
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/prepare.py", line 130, in main
      args.func(args)
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/prepare.py", line 24, in prepare_dep_dirs
      ComponentManager(
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/core.py", line 99, in wrapper
      return func(self, *args, **kwargs)
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/core.py", line 717, in prepare_dep_dirs
      downloaded_components = download_project_dependencies(
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/dependencies.py", line 340, in download_project_dependencies
      solution = solver.solve()
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/version_solver/version_solver.py", line 162, in solve
      return self._solve()
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/version_solver/version_solver.py", line 115, in _solve
      self.solve_manifest(manifest, cur_solution=cur_solution)
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/version_solver/version_solver.py", line 178, in solve_manifest
      self.solve_component(dep, manifest_path=manifest.path, cur_solution=cur_solution)
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_manager/version_solver/version_solver.py", line 218, in solve_component
      cmp_with_versions = requirement.source.versions(
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_tools/sources/web_service.py", line 145, in versions
      cmp_with_versions = client.versions(component_name=self.normalized_name(name), spec=spec)
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_tools/registry/multi_storage_client.py", line 113, in versions
      cmp_with_versions.merge(_cmp_with_versions)
    File "/home/thanhvo/.espressif/python_env/idf5.4_py3.10_env/lib/python3.10/site-packages/idf_component_tools/utils.py", line 409, in merge
      raise ValueError('Cannot merge different components')

  ValueError: Cannot merge different components

Call Stack (most recent call first):
  /home/thanhvo/esp/esp-idf/tools/cmake/project.cmake:710 (idf_build_process)
  CMakeLists.txt:6 (project)


